[character]
success_symbol = "[λ](bold)"
vicmd_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[git_commit]
only_detached = false
tag_disabled = false

[package]
display_private = true

[nodejs]
disabled = true
